### ISSUE TITLE
issue with SSL and attribute error in  execute_program_in_vm.py

### ISSUE THREAD

**Issue by thinksabin** [vmware/pyvmomi-community-samples#369]
Hi,

I tried to use the script but faced the ssl certificate issue as mentioned in the "python ssl error while trying getallvms.py #359   " and I tested with replacing the function as solution mentioned by @ldfsilva 
service_instance = connect.SmartConnectNoSSL(host=args.host,
                                                user=args.user,
                                                pwd=args.password,
                                                port=int(args.port))

But then further I faced was the attribute error

Traceback (most recent call last):
  File "execute_program_in_vm.py", line 122, in <module>
    main()
  File "execute_program_in_vm.py", line 88, in main
    tools_status = vm.guest.toolsStatus
AttributeError: 'NoneType' object has no attribute 'guest'

I am wondering if there has been updates to the api or my changes or usage is incorrect. 
thanks

**Comment by GhostofGoes** [comment]
If the VM is None then it couldn't be found. Double-check the UUID you're entering into the script matches the VM you're testing with.

**Comment by thinksabin** [comment]
UUID seems right. Here are outputs and command i used:
Output from getallvms.py

('Name       : ', 'Ubuntu')
('Template   : ', False)
('Path       : ', '[datastore1] Ubuntu/Ubuntu.vmx')
('Guest      : ', 'Ubuntu Linux (64-bit)')
('Instance UUID : ', '5239d7f0-3e96-c59b-3851-8da3d345792f')
('Bios UUID     : ', '564d8205-d2e3-1937-b46c-a83abe23ef7e')
('State      : ', 'poweredOn')
('VMware-tools: ', 'toolsOk')
('IP         : ', '192.168.2.72')

executing command in that vm:
python execute_program_in_vm.py -s 192.168.2.11 -u username -p password -v 5239d7f0-3e96-c59b-3851-8da3d345792f -r ubuntu -w ubuntu -l "/bin/touch" -f "newfilesomepyv"

Traceback (most recent call last):
  File "execute_program_in_vm.py", line 122, in <module>
    main()
  File "execute_program_in_vm.py", line 88, in main
    tools_status = vm.guest.toolsStatus
AttributeError: 'NoneType' object has no attribute 'guest'

thanks

**Comment by ldfsilva** [comment]
@thinksabin take a look at PR https://github.com/vmware/pyvmomi-community-samples/pull/370 it fixes the issue.

From your previous comment I understood that even after you have corrected the SSL issue based on https://github.com/vmware/pyvmomi-community-samples/issues/359 you still had issues, right?! 

After reproducing your steps I got the same error that you got and I noticed that the cause was really because the VM was not found. The way that the script is set it will actually look for the VM BIOS UUID and not for the VM Instance UUID. A better explanation can be found at SearchIndex[1] documentation. If you have to search VM by instance UUID some adjustments have to made to the script:

I hope it helps..

Look for this section at the doc:
instanceUuid (bool, optional, since vSphere API 4.0 ):
Should only be set when vmSearch is true. If specified, search for virtual machines whose instance UUID matches the given uuid. Otherwise, search for virtual machines whose BIOS UUID matches the given uuid.

[1] SearchIndex doc - https://github.com/vmware/pyvmomi/blob/master/docs/vim/SearchIndex.rst

**Comment by thinksabin** [comment]
thanks @ldfsilva . Your comment did help. BIOS UUID worked.
thanks again.
