### ISSUE TITLE
when to use vim and vmodl

### ISSUE THREAD

**Issue by plrnr** [vmware/pyvmomi-community-samples#419]
I am very new to this and basically trying to understand API. 
Below I can connect to a esxi and retrieve various objects. These are what I can see from https://<IP>/mob

from pyVim.connect import SmartConnect, Disconnect
c = SmartConnect(
            host=hyperVisorIP,
            user=esxiUser,
            pwd=esxiPW,
            port=httpsPort
            )

I was able to relate all the objects that I see from the https://<IP>/mob site to the Reference 'c'. Please help me if there is a way I can view/retrieve that are retrievable with a 'vim.' prefix.

For example, one of the samples uses vim.vm.ConfigSpec(). Is this viewable anywhere on the https://<IP>/mob web page?
Is there any other way to retrieve config spec of a vm through API?

**Comment by prziborowski** [comment]
[vim.vm.ConfigSpec](https://code.vmware.com/apis/196/vsphere#/doc/vim.vm.ConfigSpec.html)() is typically a user-provided object, so I don't think you'll find it anywhere in /mob.
If you navigate to a VM and its 'config', then you'll see [vim.vm.ConfigInfo](https://code.vmware.com/apis/196/vsphere#/doc/vim.vm.ConfigInfo.html)() which is fairly similar.

Note that the MOB will display the types in their wsdl format (e.g. vim.vm.ConfigInfo is VirtualMachineConfigInfo). Online documentation has that layout as well.
You can add an &vmodl to the mob url to have it display in a pyVmomi friendly format.

**Comment by paul-learner** [comment]
Thanks for responding. Referring to this sample: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/set_note.py

spec = vim.vm.ConfigSpec()
spec.annotation = args.message
task = vm.ReconfigVM_Task(spec)
tasks.wait_for_tasks(si, [task])

Can I replace above with below?

spec = vim.vm.ConfigInfo()
spec.annotation = args.message
task = vm.ReconfigVM_Task(spec)
tasks.wait_for_tasks(si, [task])

Where can I find all user-provided objects and relevant documentation? Are these only part of samples here?

**Comment by paul-learner** [comment]
It did not accept that.

>>>
>>>
>>> task = vm.ReconfigVM_Task(spec)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 385, in _InvokeMethod
    list(map(CheckField, info.params, args))
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 972, in CheckField
    % (info.name, info.type.__name__, valType.__name__))
TypeError: For "spec" expected type vim.vm.ConfigSpec, but got vim.vm.ConfigInfo

I need to get this: vim.vm.ConfigSpec, please let me know where I can get this from ?

**Comment by prziborowski** [comment]
Sorry, when I said user-provided objects, I just meant that it is something the client will pass to the server, rather than server returning to the client. So you won't see it populated in the MOB.
The links I provided in the previous comment should be the documentation on what properties can go in those objects.
I'll paste it as a link here: https://code.vmware.com/apis/196/vsphere#/doc/vim.vm.ConfigSpec.html

You can't replace ConfigSpec with ConfigInfo in a ReconfigVM_Task (https://code.vmware.com/apis/196/vsphere#/doc/vim.VirtualMachine.html#reconfigure) call because the function expects a ConfigSpec (see the Parameters section of that function).

The samples provide some guidance for what to populate with various "Spec" that are never returned by the server.
Also if there aren't pyVmomi samples, other language bindings (e.g. java) might have samples that translate in a relatively similar fashion (but that might take some getting familiar with the API first).

**Comment by paul-learner** [comment]
Thank you, appreciate you answering my questions.
