### ISSUE TITLE
Can I clone a VM from a pure ESXi 6.7?

### ISSUE THREAD

**Issue by leow1986** [vmware/pyvmomi-community-samples#628]
Without a vCenter,  when I running the clone_vm example, there was a first problem in the example `resource_pool = cluster.resourcePool`, since I don't have (can't create ) a cluster.

If I make the resource_pool as None, the example print "there was an error" and I saw the EXSi Job having a 'Clone VM' operation but it states "the operation is not supported on the object".

Is there any other way in my case that can clone a VM ? 

Thanks!

**Comment by prziborowski** [comment]
ESXi does not support the Clone API.

To re-invent the clone you would probably have to do a number of steps:
1) Use [FileManager](https://code.vmware.com/apis/358/vsphere/doc/vim.FileManager.html) to [MakeDirectory](https://code.vmware.com/apis/358/vsphere/doc/vim.FileManager.html#makeDirectory) for the cloned VM location.
2) Use [VirtualDiskManager](https://code.vmware.com/apis/358/vsphere/doc/vim.VirtualDiskManager.html) to [CopyVirtualDisk](https://code.vmware.com/apis/358/vsphere/doc/vim.VirtualDiskManager.html#copyVirtualDisk) of the source to the destination location.
3) Create the cloned VM based off the [ConfigInfo](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.ConfigInfo.html) of the source. ConfigInfo and [ConfigSpec](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.ConfigSpec.html) don't match up too perfectly, so you'd have to write something to handle the differences. Point the [fileInfo](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.FileInfo.html) to the directory you created and possibly have to name the vmx file. For the disk's [deviceSpec](https://code.vmware.com/apis/358/vsphere/doc/vim.vm.device.VirtualDeviceSpec.html), you should just operation="add" with no fileOperation because you'll be using the ones you copied in step 2. 

If you want to clone a VM that is powered on, then you'll also have to take a [snapshot](https://code.vmware.com/apis/358/vsphere/doc/vim.VirtualMachine.html#createSnapshot) prior to step 2 and call CopyVirtualDisk of the disk's parent backing because I don't think you can copy the disk while it is in use.

If you need features like guest customization, then I don't think ESX has any APIs that do that.
